### PR TITLE
Yevhen Uhnivenko w1 browsers

### PR DESCRIPTION
**Pull request by EuvhenRight**

### CODE REVIEW

**Comment by mnvacym** [comment]
Hi Yevhen, I see Javascript Module's homework is included in this PR. Can you please only include the homework for the Browser module?

**Comment by EuvhenRight** [comment]
Hi! Im trying, but I can't.

**Comment by EuvhenRight** [comment]
Can you check with JavaScript module?

**Comment by mnvacym** [comment]
> Hi! Im trying, but I can't.

Which steps did you try? And where did you get stuck?

Try creating a new branch from your `main` branch. And then commit your changes, and then create the PR.

Let me know if you still can't do it, we can have a look together

**Pull request closed without merging**
